import java.awt.Image;
import java.awt.event.KeyEvent;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class codigoSecreto extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(codigoSecreto.class.getName());
    
    int codigo = 0;
    int intentos = 0;
    int ayuda = 0;
  
    public codigoSecreto() {
        initComponents();
        
        codigo = (int)(Math.random() *900) + 100;
        lblImagen.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        panelPrincipal = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        digito2 = new javax.swing.JPasswordField();
        digito3 = new javax.swing.JPasswordField();
        digito1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        panelIngreso = new javax.swing.JPanel();
        ingresaValor = new javax.swing.JTextField();
        cajaTexto = new javax.swing.JLabel();
        botonRevelar = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        botonReiniciar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        digito2.setEditable(false);
        digito2.setBackground(new java.awt.Color(255, 102, 102));
        digito2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        digito2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        digito2.setText("$");
        digito2.setEchoChar('-');

        digito3.setEditable(false);
        digito3.setBackground(new java.awt.Color(255, 102, 102));
        digito3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        digito3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        digito3.setText("-");
        digito3.setEchoChar('-');

        digito1.setEditable(false);
        digito1.setBackground(new java.awt.Color(255, 102, 102));
        digito1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        digito1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        digito1.setText("-");
        digito1.setEchoChar('-');

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(digito1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(digito2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(digito3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(digito3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(digito2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(digito1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(204, 102, 0));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 153, 0));
        jLabel1.setText("Codigo Secreto");

        panelIngreso.setBackground(new java.awt.Color(39, 39, 39));
        panelIngreso.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(136, 136, 136)));

        ingresaValor.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        ingresaValor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        ingresaValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ingresaValorKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ingresaValorKeyTyped(evt);
            }
        });

        cajaTexto.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        cajaTexto.setForeground(new java.awt.Color(255, 204, 102));
        cajaTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cajaTexto.setText("Ingresa 3 numeros...");

        javax.swing.GroupLayout panelIngresoLayout = new javax.swing.GroupLayout(panelIngreso);
        panelIngreso.setLayout(panelIngresoLayout);
        panelIngresoLayout.setHorizontalGroup(
            panelIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ingresaValor, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelIngresoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(cajaTexto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelIngresoLayout.setVerticalGroup(
            panelIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(cajaTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ingresaValor, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
        );

        botonRevelar.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        botonRevelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-revelar-96.png"))); // NOI18N
        botonRevelar.setText("Revelar");
        botonRevelar.setToolTipText("");
        botonRevelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonRevelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonRevelar.addActionListener(this::botonRevelarActionPerformed);

        botonReiniciar.setLabel("Reiniciar");
        botonReiniciar.addActionListener(this::botonReiniciarActionPerformed);

        panelPrincipal.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelPrincipal.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelPrincipal.setLayer(panelIngreso, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelPrincipal.setLayer(botonRevelar, javax.swing.JLayeredPane.MODAL_LAYER);
        panelPrincipal.setLayer(lblImagen, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelPrincipal.setLayer(botonReiniciar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonRevelar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(botonReiniciar)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonRevelar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(botonReiniciar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRevelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRevelarActionPerformed
        // TODO add your handling code here:
        if (ayuda < 2) {

            String secreto = String.valueOf(codigo);

            if (digito1.getEchoChar() != (char) 0) {

                digito1.setText(String.valueOf(secreto.charAt(0)));
                digito1.setEchoChar((char) 0);
                ayuda++;

            } else if (digito2.getEchoChar() != (char) 0) {

                digito2.setText(String.valueOf(secreto.charAt(1)));
                digito2.setEchoChar((char) 0);
                ayuda++;

            } else if (digito3.getEchoChar() != (char) 0) {

                digito3.setText(String.valueOf(secreto.charAt(2)));
                digito3.setEchoChar((char) 0);
                ayuda++;

            }

        } else {
            JOptionPane.showMessageDialog(this, "No hay más revelaciones");
        }
    }//GEN-LAST:event_botonRevelarActionPerformed

    private void ingresaValorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresaValorKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            String input = ingresaValor.getText();
            String secreto = String.valueOf(codigo);

            if (input.length() == 3 && input.matches("\\d+")) {

                intentos++;

                if (input.charAt(0) == secreto.charAt(0)) {
                    digito1.setText(String.valueOf(input.charAt(0)));
                    digito1.setEchoChar((char) 0);
                }

                if (input.charAt(1) == secreto.charAt(1)) {
                    digito2.setText(String.valueOf(input.charAt(1)));
                    digito2.setEchoChar((char) 0);
                }

                if (input.charAt(2) == secreto.charAt(2)) {
                    digito3.setText(String.valueOf(input.charAt(2)));
                    digito3.setEchoChar((char) 0);
                }

                int numero = Integer.parseInt(input);

                if (numero > codigo) {
                    cajaTexto.setText("El codigo es mas bajo");

                } else if (numero < codigo) {
                    cajaTexto.setText("El codigo es mas alto");

                } else {
                    cajaTexto.setText("Ganaste!");

                    try {
                        URL url = new URL("https://images.vexels.com/media/users/3/202189/isolated/lists/4f3a5cb84297726d74d69dce22676f83-trofeo-numero-1-plano.png");

                        ImageIcon icon = new ImageIcon(url);

                        Image img = icon.getImage().getScaledInstance(
                                120, 120, Image.SCALE_SMOOTH
                        );

                        lblImagen.setIcon(new ImageIcon(img));
                        lblImagen.setVisible(true);

                    } catch (Exception e) {
                        System.out.println("No se pudo cargar el trofeo");
                    }

                    JOptionPane.showMessageDialog(this,
                            "Ganaste!\nCodigo correcto: " + codigo
                            + "\nIntentos: " + intentos);
                }
            }
        }

    }//GEN-LAST:event_ingresaValorKeyPressed


    
    
    private void ingresaValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresaValorKeyTyped


        
    }//GEN-LAST:event_ingresaValorKeyTyped

    private void botonReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReiniciarActionPerformed
        // TODO add your handling code here:
        codigo = (int) (Math.random() * 900) + 100;

        intentos = 0;
        ayuda = 0;

        digito1.setText("-");
        digito2.setText("-");
        digito3.setText("-");

        digito1.setEchoChar('-');
        digito2.setEchoChar('-');
        digito3.setEchoChar('-');

        ingresaValor.setText("");

        cajaTexto.setText("Ingresa 3 numeros...");

        lblImagen.setIcon(null);
        lblImagen.setVisible(false);
    }//GEN-LAST:event_botonReiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new codigoSecreto().setVisible(true));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonReiniciar;
    private javax.swing.JButton botonRevelar;
    private javax.swing.JLabel cajaTexto;
    private javax.swing.JPasswordField digito1;
    private javax.swing.JPasswordField digito2;
    private javax.swing.JPasswordField digito3;
    private javax.swing.JTextField ingresaValor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JPanel panelIngreso;
    private javax.swing.JDesktopPane panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
